using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using HansoInputTool.Models;
using NLog;
using OfficeOpenXml;

namespace HansoInputTool.Services
{
    public class TransferProgressReport
    {
        public int Current { get; set; }
        public int Total { get; set; }
        public string Message { get; set; }
    }

    public class TransferService
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// [廃車済み車両対応] 転記中にEnsureShukeiSheetで自動生成された（＝現在のTemplate.xlsxには
        /// 存在しなかった）車両シート名の一覧。転記完了後、呼び出し側（MainViewModel）がこれを見て
        /// Input.xlsx側の車両設定からも削除するかどうかの判断に使う。
        /// </summary>
        public List<string> AutoGeneratedVehicleSheets { get; } = new List<string>();

        public async Task ExecuteAsync(
            string workInputFile,
            string bundledTemplateFile,
            string outputDir,
            int period,
            int month,
            int rNum,
            List<string> allSheetNames,
            Dictionary<string, RateInfo> rates,
            ColumnMapping columnMap,
            IProgress<TransferProgressReport> progress,
            FlagDefinitionService flagService = null,
            DatabaseService dbService = null,
            string eraName = "R",
            VehicleSettingsService vehicleSettingsService = null)
        {
            await Task.Run(() =>
            {
                string folderName = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報";
                string finalOutputDir = Path.Combine(outputDir, folderName);
                Directory.CreateDirectory(finalOutputDir);

                string geppoFilename = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報.xlsx";
                string geppoFilepath = Path.Combine(finalOutputDir, geppoFilename);
                File.Copy(workInputFile, geppoFilepath, true);
                Logger.Info($"実績月報ファイルをコピーしました: {geppoFilepath}");

                string shukeiFilename = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報集計.xlsx";
                string shukeiFilepath = Path.Combine(finalOutputDir, shukeiFilename);
                File.Copy(bundledTemplateFile, shukeiFilepath, true);
                Logger.Info($"集計ファイルをコピーしました: {shukeiFilepath}");

                using var wbInput = new ExcelPackage(new FileInfo(workInputFile));
                using var wbGeppo = new ExcelPackage(new FileInfo(geppoFilepath));
                using var wbShukei = new ExcelPackage(new FileInfo(shukeiFilepath));

                var sheetsToProcess = allSheetNames?.Where(s => !s.Contains("登録")).ToList() ?? new List<string>();
                int totalSheets = sheetsToProcess.Count;
                int processedCount = 0;

                progress.Report(new TransferProgressReport { Current = 0, Total = totalSheets, Message = $"転記処理を開始します（対象: {totalSheets}シート）" });
                Logger.Info($"転記処理を開始: {totalSheets}シート");

                foreach (var sheetName in sheetsToProcess)
                {
                    progress.Report(new TransferProgressReport { Current = processedCount, Total = totalSheets, Message = $"[{processedCount + 1}/{totalSheets}] {sheetName} を処理中..." });

                    if (IsNormalSheet(sheetName))
                    {
                        ProcessNormalSheet(wbInput, wbGeppo, wbShukei, sheetName, rates, columnMap, flagService, dbService, vehicleSettingsService);
                    }
                    else if (IsEastSheet(sheetName))
                    {
                        ProcessEastSheet(wbInput, wbShukei, sheetName, columnMap);
                    }
                    else
                    {
                        Logger.Warn($"[{sheetName}] はどのシート種別にも該当しないためスキップしました。");
                    }

                    processedCount++;
                    Logger.Info($"[{sheetName}] 完了 ({processedCount}/{totalSheets})");
                }

                progress.Report(new TransferProgressReport { Current = processedCount, Total = totalSheets, Message = $"全{totalSheets}シートの転記が完了しました。保存中..." });

                // 全ての車両シート（寝台車・霊柩車・CH系）に対して
                // A1={eraName}{rNum}、B1=月 を書き込む（C1=期はファイル名に使用するのみ・セルへの記入は不要）
                foreach (var sheetWs in wbShukei.Workbook.Worksheets)
                {
                    string sn = sheetWs.Name;
                    if (IsNormalSheet(sn) || IsEastSheet(sn))
                    {
                        sheetWs.Cells["A1"].Value = $"{eraName}{rNum}";
                        sheetWs.Cells["B1"].Value = month;
                        Logger.Info($"集計ファイル [{sn}] に A1={eraName}{rNum}, B1={month} を書き込みました。");
                    }
                }
                foreach (var sheetWs in wbGeppo.Workbook.Worksheets)
                {
                    string sn = sheetWs.Name;
                    if (IsNormalSheet(sn) || IsEastSheet(sn))
                    {
                        sheetWs.Cells["A1"].Value = $"{eraName}{rNum}";
                        sheetWs.Cells["B1"].Value = month;
                        Logger.Info($"月報ファイル [{sn}] に A1={eraName}{rNum}, B1={month} を書き込みました。");
                    }
                }

                // [給油機能] DB使用時は給油記録を実績月報（wbGeppo）の給油管理表シートへ書き込む
                if (dbService != null)
                {
                    WriteFuelSheet(wbGeppo, dbService.GetAllFuelRecordsForCurrentSession());
                }

                // [並び替え対応] 自動生成された廃車済み車両シート等も含めて、
                // ①CH富士吉田→②CH大月→③CH東富士→④東日本セレモニーの順に並べ替える
                ReorderShukeiSheets(wbShukei);

                // [月間集計対応] 集計ファイルの「月間集計」シートは今まで自動更新されておらず、
                // 車両の追加・削除・廃車が反映されていなかったため、転記の都度、現在の車両構成で再作成する。
                UpdateShukeiMonthlySummary(wbInput, wbShukei, flagService, dbService);

                wbShukei.Save();
                wbGeppo.Save();

                // [No.6修正] TransferService内でのDBクリアを削除。
                // DBクリアは呼び出し元(MainViewModel.Transfer.cs)の転記完了後処理で一元管理する。
            });
        }

        // ===== シート種別の一元判定ヘルパー =====
        private static readonly string[] NormalSheetKeywords = { "寝台車", "霊柩車", "CH富士吉田", "CH大月", "CH東富士" };
        private static readonly string[] EastSheetKeywords  = { "東日本セレモニー", "東日本" };

        // シート順序：①CH富士吉田 → ②CH大月 → ③CH東富士 → ④東日本セレモニー
        private static readonly string[] BranchOrder = { "CH富士吉田", "CH大月", "CH東富士", "東日本セレモニー" };

        /// <summary>
        /// [並び替え対応] 集計ファイル(wbShukei)のシート順を支社名ごとに整える。
        /// 「月間集計」は常に先頭、「Template」ひな形シートは常に末尾に固定する。
        /// 廃車済み車両などで自動生成されたシート（末尾に追加される）も、この処理で正しい位置に移動する。
        /// </summary>
        private void ReorderShukeiSheets(ExcelPackage wbShukei)
        {
            try
            {
                var monthly = wbShukei.Workbook.Worksheets.FirstOrDefault(w => w.Name == "月間集計");
                var templateWs = wbShukei.Workbook.Worksheets.FirstOrDefault(w => w.Name == "Template");

                var orderedNames = wbShukei.Workbook.Worksheets
                    .Where(ws => ws.Name != "月間集計" && ws.Name != "Template" && !ws.Name.Contains("登録"))
                    .Select(ws =>
                    {
                        int branchOrder = Array.FindIndex(BranchOrder, b => ws.Name.Contains(b));
                        if (branchOrder < 0) branchOrder = BranchOrder.Length; // 不明な支社名は末尾扱い
                        var m = Regex.Match(ws.Name, @"\d+$");
                        int number = m.Success && int.TryParse(m.Value, out var n) ? n : int.MaxValue;
                        return new { ws.Name, BranchOrder = branchOrder, Number = number };
                    })
                    .OrderBy(v => v.BranchOrder)
                    .ThenBy(v => v.Number)
                    .ThenBy(v => v.Name, StringComparer.Ordinal)
                    .Select(v => v.Name)
                    .ToList();

                // 月間集計を先頭に固定
                if (monthly != null)
                    wbShukei.Workbook.Worksheets.MoveBefore(monthly.Index, 1);

                for (int i = orderedNames.Count - 1; i >= 0; i--)
                {
                    var ws = wbShukei.Workbook.Worksheets.FirstOrDefault(x => x.Name == orderedNames[i]);
                    if (ws == null) continue;
                    if (monthly != null) wbShukei.Workbook.Worksheets.MoveAfter(ws.Index, 1);
                    else                 wbShukei.Workbook.Worksheets.MoveBefore(ws.Index, 1);
                }

                // Templateひな形シートは常に末尾に固定
                if (templateWs != null)
                    wbShukei.Workbook.Worksheets.MoveToEnd(templateWs.Name);

                Logger.Info("集計ファイルのシート順を並べ替えました。");
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "集計ファイルのシート並び替え中にエラーが発生しました。");
            }
        }

        /// <summary>
        /// [月間集計対応] 集計ファイル(wbShukei)の「月間集計」シートを、現在の車両シート構成で作り直す。
        /// ExcelHandler.MonthlySummary.cs の UpdateMonthlySummarySheetIfNeeded と同じロジックだが、
        /// 従来はInput.xlsx側にしか適用されておらずTemplate.xlsx（集計ファイル）側は更新されていなかったため、
        /// 転記の都度こちらでも実行することで、新規追加・廃車済み車両を含めて最新の状態に同期する。
        ///
        /// [デザイン対応] 「月間集計」はExcelの「テーブル」機能（縞模様等の表スタイル）で構成されており、
        /// その表の範囲（ref）は車両数が変わっても自動では広がらない。単純にセルへ値を書き込むだけでは、
        /// 表の範囲外にはみ出した行の見た目（縞模様・罫線・数値の書式）が一切適用されず崩れてしまうため、
        /// EPPlus 8 の ExcelTable.DataRows API でテーブル自体の行数を車両数+合計行に合わせて増減させる。
        /// </summary>
        private void UpdateShukeiMonthlySummary(ExcelPackage wbInput, ExcelPackage wbShukei, FlagDefinitionService flagService, DatabaseService dbService)
        {
            try
            {
                var summarySheet = wbShukei.Workbook.Worksheets.FirstOrDefault(w => w.Name == "月間集計");
                if (summarySheet == null)
                {
                    Logger.Warn("集計ファイルに『月間集計』シートが見つからないため、更新をスキップしました。");
                    return;
                }

                var allVehicleSheets = wbShukei.Workbook.Worksheets
                    .Where(ws => ws.Name != "月間集計" && ws.Name != "Template" && !ws.Name.Contains("登録"))
                    .Select(ws => ws.Name)
                    .Select(name =>
                    {
                        int branchOrder = Array.FindIndex(BranchOrder, b => name.Contains(b));
                        if (branchOrder < 0) branchOrder = BranchOrder.Length;
                        var m = Regex.Match(name, @"\d+$");
                        int number = m.Success && int.TryParse(m.Value, out var n) ? n : int.MaxValue;
                        return new { Name = name, BranchOrder = branchOrder, Number = number };
                    })
                    .OrderBy(v => v.BranchOrder)
                    .ThenBy(v => v.Number)
                    .ThenBy(v => v.Name, StringComparer.Ordinal)
                    .Select(v => v.Name)
                    .ToList();

                var flags = flagService?.Flags ?? new List<FlagDefinition>().AsReadOnly();
                int endCol = 11 + flags.Count;
                // [不要な0対応] 過去に存在したフラグ列など、現在のフラグ数を超えた古いデータが
                // テーブル外の列に残ってしまうことがあるため、少し広めの範囲までクリアする。
                int clearEndCol = Math.Max(endCol, 20);

                // [デザイン対応] 月間集計の表（ヘッダー行の次の行からデータが始まる）の行数を実車両数+合計行に合わせる
                var table = summarySheet.Tables?.FirstOrDefault();
                int dataStartRow;
                if (table != null && allVehicleSheets.Count > 0)
                {
                    int desiredDataRows = allVehicleSheets.Count + 1; // 車両行 + 合計行
                    int currentDataRows = table.Address.End.Row - table.Address.Start.Row; // ヘッダー行を除いた行数

                    // [太字対応] 行を追加する前に、正しい書式を持つ1行目（データの最初の行）のスタイルを控えておく。
                    // ExcelTable.DataRows.AddNewRowsは直前の行（今までの合計行など）の書式をコピーしてしまうため、
                    // 新規追加された行がその書式（太字・罫線）を引き継いでしまう不具合を防ぐ。
                    int normalRowRef = table.Address.Start.Row + 1;
                    var normalStyleIds = new int[clearEndCol];
                    for (int col = 1; col <= clearEndCol; col++)
                        normalStyleIds[col - 1] = summarySheet.Cells[normalRowRef, col].StyleID;

                    if (desiredDataRows > currentDataRows)
                        table.DataRows.AddNewRows(desiredDataRows - currentDataRows);
                    else if (desiredDataRows < currentDataRows)
                        table.DataRows.DeleteRows(desiredDataRows, currentDataRows - desiredDataRows);

                    dataStartRow = table.Address.Start.Row + 1;

                    // 全データ行（合計行になる最終行を含む）に、いったん正しい通常行の書式を適用し直す。
                    // 合計行の太字・上罫線は、この後の書き込み処理で改めて明示的に設定する。
                    for (int row = dataStartRow; row <= table.Address.End.Row; row++)
                        for (int col = 1; col <= clearEndCol; col++)
                            summarySheet.Cells[row, col].StyleID = normalStyleIds[col - 1];
                }
                else
                {
                    // テーブルが見つからない場合は従来通り固定行から開始（見た目の自動調整は行われない）
                    dataStartRow = 4;
                    if (table == null)
                        Logger.Warn("月間集計シートにテーブルが見つからなかったため、表の行数調整はスキップしました。");
                }

                int clearEndRow = table != null ? table.Address.End.Row : dataStartRow + 69;
                for (int row = dataStartRow; row <= clearEndRow; row++)
                    for (int col = 1; col <= clearEndCol; col++)
                    {
                        summarySheet.Cells[row, col].Value = null;
                        summarySheet.Cells[row, col].Formula = null;
                    }

                for (int i = 0; i < allVehicleSheets.Count; i++)
                {
                    string sheetName = allVehicleSheets[i];
                    int currentRow = dataStartRow + i;
                    string branch = BranchOrder.FirstOrDefault(b => sheetName.Contains(b)) ?? "";
                    var numMatch = Regex.Match(sheetName, @"\d+$");
                    object number = numMatch.Success && int.TryParse(numMatch.Value, out int num) ? (object)num : null;

                    try
                    {
                        string safeSheetName = $"'{sheetName}'";

                        summarySheet.Cells[currentRow, 1].Value = $"No.{i + 1}";
                        summarySheet.Cells[currentRow, 2].Value = branch;
                        summarySheet.Cells[currentRow, 3].Value = number;

                        summarySheet.Cells[currentRow, 4].Formula  = $"{safeSheetName}!E4";
                        summarySheet.Cells[currentRow, 5].Formula  = $"{safeSheetName}!G4";
                        summarySheet.Cells[currentRow, 6].Formula  = $"IFERROR(E{currentRow}/D{currentRow},0)";
                        summarySheet.Cells[currentRow, 7].Formula  = $"{safeSheetName}!G4";
                        summarySheet.Cells[currentRow, 8].Formula  = $"{safeSheetName}!H4";
                        summarySheet.Cells[currentRow, 9].Formula  = $"{safeSheetName}!I4";
                        summarySheet.Cells[currentRow, 10].Formula = $"SUM(H{currentRow}:I{currentRow})";
                        summarySheet.Cells[currentRow, 11].Formula = $"{safeSheetName}!K4";

                        // [フラグ情報対応] 実績月報集計にはフラグ情報を記入しない方針になったため、
                        // フラグ列への書き込みは行わない（列自体は上でクリア済み）。
                    }
                    catch (Exception ex)
                    {
                        Logger.Error(ex, $"月間集計 Row {currentRow} ({sheetName}) のデータ設定中にエラーが発生しました");
                    }
                }

                if (allVehicleSheets.Count > 0)
                {
                    // [デザイン対応] 合計行は必ず最後の車両行の直後（テーブルの最終行）に配置する
                    int totalRow = dataStartRow + allVehicleSheets.Count;
                    int lastDataRow = totalRow - 1;
                    summarySheet.Cells[totalRow, 1].Value = "合　計";
                    summarySheet.Cells[totalRow, 4].Formula  = $"SUM(D{dataStartRow}:D{lastDataRow})";
                    summarySheet.Cells[totalRow, 5].Formula  = $"SUM(E{dataStartRow}:E{lastDataRow})";
                    summarySheet.Cells[totalRow, 6].Formula  = $"IFERROR(E{totalRow}/D{totalRow},0)";
                    summarySheet.Cells[totalRow, 7].Formula  = $"SUM(G{dataStartRow}:G{lastDataRow})";
                    summarySheet.Cells[totalRow, 8].Formula  = $"SUM(H{dataStartRow}:H{lastDataRow})";
                    summarySheet.Cells[totalRow, 9].Formula  = $"SUM(I{dataStartRow}:I{lastDataRow})";
                    summarySheet.Cells[totalRow, 10].Formula = $"SUM(J{dataStartRow}:J{lastDataRow})";
                    summarySheet.Cells[totalRow, 11].Formula = $"SUM(K{dataStartRow}:K{lastDataRow})";

                    // [デザイン対応] 合計行は太字＋上罫線で強調する（通常行と見分けられるように）
                    var totalRange = summarySheet.Cells[totalRow, 1, totalRow, 11];
                    totalRange.Style.Font.Bold = true;
                    totalRange.Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                    // [レイアウト対応] 「合計」の文字をA列・B列にまたがって中央に表示する。
                    // ExcelTableの範囲内はセル結合と相性が悪い（行数の自動増減処理と衝突するおそれがある）ため、
                    // セル結合ではなく「選択範囲内で中央」表示＋境界線の非表示で見た目だけ揃える。
                    var totalLabelRange = summarySheet.Cells[totalRow, 1, totalRow, 2];
                    totalLabelRange.Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.CenterContinuous;
                    summarySheet.Cells[totalRow, 1].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.None;
                    summarySheet.Cells[totalRow, 2].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.None;
                }
                else
                {
                    summarySheet.Cells[dataStartRow, 1].Value = "（車両データなし）";
                }

                wbShukei.Workbook.CalcMode = ExcelCalcMode.Automatic;
                Logger.Info($"集計ファイルの月間集計シートを更新しました（対象車両数: {allVehicleSheets.Count}）。");
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "集計ファイルの月間集計シート更新中にエラーが発生しました。");
            }
        }

        /// <summary>Excel使用時（DB未使用時）に、Input.xlsx上のフラグ列がONの行数を数える。</summary>
        private int GetFlagCountFromExcel(ExcelPackage wbInput, string sheetName, int excelColumn)
        {
            var ws = wbInput.Workbook.Worksheets.FirstOrDefault(s => s.Name == sheetName);
            if (ws == null) return 0;
            var totalRowIndex = FindTotalRow(ws);
            if (totalRowIndex == -1) return 0;
            int count = 0;
            for (int r = 3; r < totalRowIndex; r++)
                if (GetInt(ws.Cells[r, excelColumn].Value) == 1) count++;
            return count;
        }

        private static bool IsNormalSheet(string sheetName) =>
            NormalSheetKeywords.Any(kw => sheetName.Contains(kw));

        private static bool IsEastSheet(string sheetName) =>
            EastSheetKeywords.Any(kw => sheetName.Contains(kw));
        // ==========================================

        private void ProcessNormalSheet(ExcelPackage wbInput, ExcelPackage wbGeppo, ExcelPackage wbShukei, string sheetName, Dictionary<string, RateInfo> rates, ColumnMapping columnMap, FlagDefinitionService flagService = null, DatabaseService dbService = null, VehicleSettingsService vehicleSettingsService = null)
        {
            var wsIn = wbInput.Workbook.Worksheets[sheetName];
            var wsGeppo = wbGeppo.Workbook.Worksheets[sheetName];
            var totalRowIdx = FindTotalRow(wsIn);
            if (totalRowIdx == -1) return;

            var normalMap = columnMap.NormalSheet;
            var shukeiMap = columnMap.ShukeiSheet;

            string rateCategory = sheetName.Contains("霊柩車") ? "霊柩車" : "寝台車";
            if (!rates.TryGetValue(rateCategory, out var ratesForSheet))
            {
                Logger.Warn($"シート '{sheetName}' に対応する料金カテゴリ '{rateCategory}' が見つかりませんでした。");
                return;
            }

            // [深夜料金バグ修正] 車両設定（深夜入力方式）を優先し、未設定時のみ「大月」判定にフォールバックする。
            // これにより設定画面で深夜入力方式を「深夜時間」に変更した車両でも正しく計算されるようになる。
            bool isOotsuki = vehicleSettingsService?.IsFeeMode(sheetName) ?? sheetName.Contains("大月");
            double totalKihon = 0, totalSoko = 0, totalShinya = 0, totalSum = 0;

            // 金額ありフラグ（WithAmount）を取得して料金計算に使う
            var withAmountFlags = flagService?.Flags
                .Where(f => f.Type == FlagType.WithAmount)
                .ToList() ?? new List<FlagDefinition>();

            // ── DB使用時：DBからデータを読んでwsGeppoに書き込む ──
            if (dbService != null)
            {
                var flags   = flagService?.Flags ?? new System.Collections.ObjectModel.ReadOnlyCollection<FlagDefinition>(new List<FlagDefinition>());
                var dbRows  = dbService.GetSheetData(sheetName, flags);
                int writeRow = 3;

                // [No.3修正] DB使用時の集計値はdbRowsから直接計算する
                int dbTotalHanso = 0;
                double dbTotalYuryoKm = 0, dbTotalMuryoKm = 0;
                // [転記出力修正] 延実在車輌数／使用日数は「同じ日に何件動いても1日として1回」カウントする。
                // 同一日に複数行（複数搬送）がある場合でも重複カウントしないよう、日付の集合(HashSet)で管理する。
                var usedDaysSet = new HashSet<int>();

                foreach (var dbRow in dbRows)
                {
                    int hansoVal    = dbRow.C_Hanso ?? 0;
                    double yuryoKm  = dbRow.D_YuryoKm ?? 0;
                    double muryoKm  = dbRow.E_MuryoKm ?? 0;
                    double rowKihon = 0, rowSoko = 0, rowShinya = 0;

                    // Excelのwsに値を書き込む（geppoの行として）
                    wsGeppo.Cells[writeRow, normalMap.Day].Value        = dbRow.B_Day;
                    wsGeppo.Cells[writeRow, normalMap.HansoCount].Value = (object)hansoVal;
                    wsGeppo.Cells[writeRow, normalMap.YuryoKm].Value    = (object)yuryoKm;
                    wsGeppo.Cells[writeRow, normalMap.MuryoKm].Value    = (object)muryoKm;

                    // [No.1修正] 深夜の入力値（分 or 料金）を入力欄列に書く。
                    // ShinyaFee列への書き込みは後続の「計算後のrowShinya」のみとし、
                    // ここでは大月以外のShinyaMinutes列のみ書く。
                    if (isOotsuki)
                    {
                        // 大月は入力値をそのまま ShinyaFee 列に書く（後続のrowShinya代入と同値）
                        // ※ 後続で wsGeppo.ShinyaFee に rowShinya を書くため、ここでは書かない
                    }
                    else
                    {
                        wsGeppo.Cells[writeRow, normalMap.ShinyaMinutes].Value = (object)(dbRow.K_LateMinutes ?? 0);
                    }

                    // フラグ書き込み
                    foreach (var flag in flags)
                    {
                        int? fv = dbRow.FlagValues?.GetValueOrDefault(flag.Id);
                        wsGeppo.Cells[writeRow, flag.ExcelColumn].Value = fv == 1 ? 1 : (object)null;
                    }

                    if (hansoVal > 0)
                    {
                        rowKihon = ratesForSheet.BaseFee;
                        if (yuryoKm > 0)
                            rowSoko = (Math.Floor(yuryoKm / 10) + 1) * ratesForSheet.MileageFee;

                        foreach (var flag in withAmountFlags)
                        {
                            bool flagOn = (dbRow.FlagValues?.GetValueOrDefault(flag.Id) == 1);
                            if (!flagOn) continue;

                            bool applyBase    = flag.TargetFee == TargetFee.BaseFee || flag.TargetFee == TargetFee.Both;
                            bool applyMileage = flag.TargetFee == TargetFee.MileageFee || flag.TargetFee == TargetFee.Both;

                            if (flag.AmountType == AmountType.Rate && flag.AmountValue.HasValue)
                            {
                                if (applyBase)    rowKihon = Math.Floor(ratesForSheet.BaseFee * flag.AmountValue.Value);
                                if (applyMileage) rowSoko  = Math.Floor(rowSoko               * flag.AmountValue.Value);
                            }
                            else if (flag.AmountType == AmountType.Fixed && flag.AmountValue.HasValue)
                            {
                                if (applyBase)    rowKihon = flag.AmountValue.Value;
                                if (applyMileage) rowSoko  = flag.AmountValue.Value;
                            }
                        }
                        if (isOotsuki)
                            rowShinya = dbRow.H_LateFeeOotsuki ?? 0;
                        else
                        {
                            double shinyaMin = dbRow.K_LateMinutes ?? 0;
                            if (shinyaMin > 0)
                            {
                                double numBlocks   = Math.Floor(shinyaMin / 30) + 1;
                                double variableRyo = numBlocks * ratesForSheet.LateNightUnitFee;
                                rowShinya = variableRyo + ratesForSheet.LateNightFixedFee;
                            }
                        }
                    }

                    wsGeppo.Cells[writeRow, normalMap.KihonFee].Value  = (object)rowKihon;
                    wsGeppo.Cells[writeRow, normalMap.SokoFee].Value   = (object)rowSoko;
                    // [No.1修正] ShinyaFee列への書き込みはここ1か所のみ（計算済みrowShinyaを使用）
                    wsGeppo.Cells[writeRow, normalMap.ShinyaFee].Value = (object)rowShinya;
                    double rowTotal = rowKihon + rowSoko + rowShinya;
                    wsGeppo.Cells[writeRow, normalMap.TotalFee].Value  = (object)rowTotal;

                    totalKihon  += rowKihon;
                    totalSoko   += rowSoko;
                    totalShinya += rowShinya;
                    totalSum    += rowTotal;

                    // [No.3修正] dbRowsから集計値を直接計算
                    // [転記出力修正] 使用日数・延実在車輌数は搬送件数ではなく「稼働した日」の数として数える
                    if (dbRow.B_Day.HasValue) usedDaysSet.Add(dbRow.B_Day.Value);
                    dbTotalHanso  += hansoVal;
                    dbTotalYuryoKm += yuryoKm;
                    dbTotalMuryoKm += muryoKm;

                    writeRow++;
                }

                int dbTotalDays = usedDaysSet.Count;

                // [No.4修正] 実績月報（wsGeppo）103行目（合計行）にも使用・搬送・有料・無料の集計値を書き込む。
                // 合計行にはテンプレート由来のCOUNT/SUM数式が残っているが、EPPlusは保存時に再計算しないため
                // 数式のままだと未計算（空欄）になる。集計ファイルと同じ値を直接書き込んで確実に反映する。
                wsGeppo.Cells[totalRowIdx, normalMap.Day].Value        = dbTotalDays > 0 ? (object)dbTotalDays : null;
                wsGeppo.Cells[totalRowIdx, normalMap.HansoCount].Value = dbTotalHanso > 0 ? (object)dbTotalHanso : null;
                wsGeppo.Cells[totalRowIdx, normalMap.YuryoKm].Value    = dbTotalYuryoKm > 0 ? (object)dbTotalYuryoKm : null;
                wsGeppo.Cells[totalRowIdx, normalMap.MuryoKm].Value    = dbTotalMuryoKm > 0 ? (object)dbTotalMuryoKm : null;

                // [No.3修正] 集計ファイルへの書き込みをここで行い、CalculateTotals()を使わない
                // [廃車済み車両対応] 該当シートが集計ファイルに無ければ自動生成してから書き込む
                var wsShukeiForDb = EnsureShukeiSheet(wbShukei, sheetName);
                if (wsShukeiForDb != null)
                {
                    wsShukeiForDb.Cells[shukeiMap.Days].Value    = dbTotalDays;
                    wsShukeiForDb.Cells[shukeiMap.Hanso].Value   = dbTotalHanso;
                    wsShukeiForDb.Cells[shukeiMap.YuryoKm].Value = dbTotalYuryoKm;
                    wsShukeiForDb.Cells[shukeiMap.MuryoKm].Value = dbTotalMuryoKm;
                    wsShukeiForDb.Cells[shukeiMap.Total].Value   = totalSum > 0 ? totalSum : null;
                }
            }
            else
            {
            // ── Excel使用時（従来）：wsInから直接読む ──
            for (int row = 3; row < totalRowIdx; row++)
            {
                int hansoVal = GetInt(wsIn.Cells[row, normalMap.HansoCount].Value);
                double rowKihon = 0, rowSoko = 0, rowShinya = 0;

                if (hansoVal > 0)
                {
                    double yuryoKmVal = GetDouble(wsIn.Cells[row, normalMap.YuryoKm].Value);

                    // 動的フラグによる基本料金計算
                    rowKihon = ratesForSheet.BaseFee;
                    if (yuryoKmVal > 0)
                        rowSoko = (Math.Floor(yuryoKmVal / 10) + 1) * ratesForSheet.MileageFee;

                    foreach (var flag in withAmountFlags)
                    {
                        bool flagOn = GetInt(wsIn.Cells[row, flag.ExcelColumn].Value) == 1;
                        if (!flagOn) continue;

                        bool applyBase    = flag.TargetFee == TargetFee.BaseFee || flag.TargetFee == TargetFee.Both;
                        bool applyMileage = flag.TargetFee == TargetFee.MileageFee || flag.TargetFee == TargetFee.Both;

                        if (flag.AmountType == AmountType.Rate && flag.AmountValue.HasValue)
                        {
                            if (applyBase)    rowKihon = Math.Floor(ratesForSheet.BaseFee   * flag.AmountValue.Value);
                            if (applyMileage) rowSoko  = Math.Floor(rowSoko                  * flag.AmountValue.Value);
                        }
                        else if (flag.AmountType == AmountType.Fixed && flag.AmountValue.HasValue)
                        {
                            if (applyBase)    rowKihon = flag.AmountValue.Value;
                            if (applyMileage) rowSoko  = flag.AmountValue.Value;
                        }
                    }

                    if (isOotsuki)
                    {
                        rowShinya = GetDouble(wsIn.Cells[row, normalMap.ShinyaFee].Value);
                    }
                    else
                    {
                        double shinyaMin = GetDouble(wsIn.Cells[row, normalMap.ShinyaMinutes].Value);
                        if (shinyaMin > 0)
                        {
                            double numBlocks = Math.Floor(shinyaMin / 30) + 1;
                            double variableRyo = numBlocks * ratesForSheet.LateNightUnitFee;
                            rowShinya = variableRyo + ratesForSheet.LateNightFixedFee;
                        }
                    }
                }

                wsGeppo.Cells[row, normalMap.KihonFee].Value = rowKihon > 0 ? rowKihon : null;
                wsGeppo.Cells[row, normalMap.SokoFee].Value = rowSoko > 0 ? rowSoko : null;
                wsGeppo.Cells[row, normalMap.ShinyaFee].Value = rowShinya > 0 ? rowShinya : null;
                double rowTotal = rowKihon + rowSoko + rowShinya;
                wsGeppo.Cells[row, normalMap.TotalFee].Value = rowTotal > 0 ? rowTotal : null;

                totalKihon += rowKihon;
                totalSoko += rowSoko;
                totalShinya += rowShinya;
                totalSum += rowTotal;
            }
            } // end Excel使用時

            wsGeppo.Cells[totalRowIdx, normalMap.KihonFee].Value = totalKihon > 0 ? totalKihon : null;
            wsGeppo.Cells[totalRowIdx, normalMap.SokoFee].Value = totalSoko > 0 ? totalSoko : null;
            wsGeppo.Cells[totalRowIdx, normalMap.ShinyaFee].Value = totalShinya > 0 ? totalShinya : null;
            wsGeppo.Cells[totalRowIdx, normalMap.TotalFee].Value = totalSum > 0 ? totalSum : null;

            // [No.3修正] DB使用時は集計ファイルへの書き込みを上のDBブロック内で完了済み。
            // Excel使用時のみ CalculateTotals() でwsInから集計してここで書き込む。
            if (dbService == null)
            {
                var totals = CalculateTotals(wsIn, totalRowIdx, normalMap);

                // [No.4修正] 実績月報（wsGeppo）103行目（合計行）にも使用・搬送・有料・無料の集計値を書き込む。
                // 合計行にはテンプレート由来のCOUNT/SUM数式が残っているが、EPPlusは保存時に再計算しないため
                // 数式のままだと未計算（空欄）になる。集計ファイルと同じ値を直接書き込んで確実に反映する。
                wsGeppo.Cells[totalRowIdx, normalMap.Day].Value        = totals.days > 0 ? (object)totals.days : null;
                wsGeppo.Cells[totalRowIdx, normalMap.HansoCount].Value = totals.hanso > 0 ? (object)totals.hanso : null;
                wsGeppo.Cells[totalRowIdx, normalMap.YuryoKm].Value    = totals.yuryoKm > 0 ? (object)totals.yuryoKm : null;
                wsGeppo.Cells[totalRowIdx, normalMap.MuryoKm].Value    = totals.muryoKm > 0 ? (object)totals.muryoKm : null;

                // [廃車済み車両対応] 該当シートが集計ファイルに無ければ自動生成してから書き込む
                var wsShukeiForExcel = EnsureShukeiSheet(wbShukei, sheetName);
                if (wsShukeiForExcel != null)
                {
                    wsShukeiForExcel.Cells[shukeiMap.Days].Value    = totals.days;
                    wsShukeiForExcel.Cells[shukeiMap.Hanso].Value   = totals.hanso;
                    wsShukeiForExcel.Cells[shukeiMap.YuryoKm].Value = totals.yuryoKm;
                    wsShukeiForExcel.Cells[shukeiMap.MuryoKm].Value = totals.muryoKm;
                    wsShukeiForExcel.Cells[shukeiMap.Total].Value   = totalSum > 0 ? totalSum : null;
                }
            }
        }

        private (int days, int hanso, double yuryoKm, double muryoKm) CalculateTotals(ExcelWorksheet ws, int totalRowIdx, SheetColumnMap map)
        {
            int totalHanso = 0;
            double totalYuryoKm = 0, totalMuryoKm = 0;
            // [転記出力修正] 延実在車輌数／使用日数は「同じ日に何件動いても1日として1回」カウントする。
            // 同一日に複数行（複数搬送）が入力されていても重複カウントしないよう、日付の集合(HashSet)で管理する。
            var usedDaysSet = new HashSet<object>();
            for (int row = 3; row < totalRowIdx; row++)
            {
                var dayVal = ws.Cells[row, map.Day].Value;
                if (dayVal != null) usedDaysSet.Add(dayVal);
                totalHanso += GetInt(ws.Cells[row, map.HansoCount].Value);
                totalYuryoKm += GetDouble(ws.Cells[row, map.YuryoKm].Value);
                totalMuryoKm += GetDouble(ws.Cells[row, map.MuryoKm].Value);
            }
            return (usedDaysSet.Count, totalHanso, totalYuryoKm, totalMuryoKm);
        }

        /// <summary>
        /// [廃車済み車両対応] 集計ファイル(wbShukei)に対象シートが存在しない場合に自動生成する。
        /// 廃車等により現在のTemplate.xlsxからは削除済みの車両でも、過去のInput.xlsxを読み込んで
        /// 転記すると出力から漏れてしまっていたため、その場で「Template」シートから複製して対応する。
        /// </summary>
        private ExcelWorksheet EnsureShukeiSheet(ExcelPackage wbShukei, string sheetName)
        {
            // 完全一致 → CH富士吉田の接頭辞なしシート名に対応するEndsWithフォールバックの順に探す
            var existing = wbShukei.Workbook.Worksheets.FirstOrDefault(ws => ws.Name == sheetName)
                        ?? wbShukei.Workbook.Worksheets.FirstOrDefault(ws => ws.Name.EndsWith(sheetName));
            if (existing != null) return existing;

            var templateWs = wbShukei.Workbook.Worksheets.FirstOrDefault(ws => ws.Name == "Template");
            if (templateWs == null)
            {
                Logger.Warn($"[{sheetName}] は集計ファイルに存在せず、コピー元の『Template』シートも見つからなかったため出力できませんでした。");
                return null;
            }

            var newWs = wbShukei.Workbook.Worksheets.Add(sheetName, templateWs);
            PopulateNewShukeiSheetCells(newWs, sheetName);
            if (!AutoGeneratedVehicleSheets.Contains(sheetName))
                AutoGeneratedVehicleSheets.Add(sheetName);
            Logger.Info($"[{sheetName}] は集計ファイルに存在しなかったため『Template』から自動生成しました（廃車済みなどでTemplate.xlsxに未登録の車両の可能性があります）。");
            return newWs;
        }

        /// <summary>
        /// [廃車済み車両対応] Template.xlsxのSetupNewSheetCells相当の処理。
        /// 新規作成した車両シートの支社名・車輌番号のセルを、シート名から解析して埋める。
        /// 東日本セレモニー系はB4=支社名／C4=車輌番号、それ以外はD1=支社名+種別／H1=車輌番号。
        /// </summary>
        private void PopulateNewShukeiSheetCells(ExcelWorksheet ws, string sheetName)
        {
            // [不具合修正] 実際のシート構成を確認したところ、集計ファイルの車両シートは
            // 車種に関わらずB4(支社名)・C4(車輌番号)のみを使用しており、1行目にD1/H1のような
            // 項目は存在しない（1行目はA1=元号,B1=月,C1='月分'のみ）。誤って余分な文字を
            // 入れてしまっていたため、D1/H1への書き込みは廃止する。
            string branch = BranchOrder.FirstOrDefault(b => sheetName.Contains(b)) ?? sheetName.Trim();
            var numberMatch = Regex.Match(sheetName, @"\d+$");
            int? vehicleNumber = numberMatch.Success && int.TryParse(numberMatch.Value, out int num) ? num : (int?)null;

            ws.Cells["B4"].Value = branch;
            if (vehicleNumber.HasValue)
                ws.Cells["C4"].Value = vehicleNumber.Value;
        }

        // ===== 給油管理表への書き込み =====
        // Excelのシートタブ名は表内のタイトル文字列と異なる場合があるため、
        // 「給油管理」という文字列を含むシートを対象として検索する（例:「給油管理表」「寝台車　給油管理」など）。
        private const string FuelSheetKeyword = "給油管理";

        /// <summary>
        /// DBに登録された給油記録を、実績月報（wbGeppo）内の給油管理シートへ書き込む。
        /// 車両ごとの列位置はハードコードせず、車両名の見出しセルを起点に実行時に探す
        /// （Template.xlsxの列レイアウトが変わっても追従できるようにするため）。
        /// </summary>
        private void WriteFuelSheet(ExcelPackage wbGeppo, List<FuelRecord> fuelRecords)
        {
            if (fuelRecords == null || fuelRecords.Count == 0) return;

            var ws = wbGeppo.Workbook.Worksheets.FirstOrDefault(s => s.Name.Contains(FuelSheetKeyword));
            if (ws == null)
            {
                Logger.Warn($"「{FuelSheetKeyword}」を含むシートが見つからないため、給油記録の書き込みをスキップしました。");
                return;
            }

            foreach (var group in fuelRecords.GroupBy(f => f.VehicleSheetName))
            {
                var block = FindFuelVehicleBlock(ws, group.Key);
                if (block == null)
                {
                    Logger.Warn($"「{FuelSheetKeyword}」を含むシートに車両「{group.Key}」の列が見つからないため、この車両の給油記録はスキップしました。");
                    continue;
                }

                var (dayCol, kmCol, litersCol, firstDataRow) = block.Value;

                int row = firstDataRow;
                foreach (var fuel in group.OrderBy(f => f.Day))
                {
                    // 既に値が入っている行はスキップして次の空き行へ
                    while (ws.Cells[row, dayCol].Value != null) row++;
                    ws.Cells[row, dayCol].Value     = fuel.Day;
                    ws.Cells[row, kmCol].Value      = fuel.OdometerKm;
                    ws.Cells[row, litersCol].Value  = fuel.Liters;
                    row++;
                }
                Logger.Info($"「{FuelSheetKeyword}」を含むシート[{group.Key}] に給油記録{group.Count()}件を書き込みました。");
            }
        }

        /// <summary>
        /// 給油管理表シート内で指定車両の列ブロック（日・給油時Km・給油㍑数の列番号とデータ開始行）を探す。
        /// 車両名の見出しセルを見つけ、その付近で「日」ヘッダーの位置から列を特定する。
        /// </summary>
        private (int dayCol, int kmCol, int litersCol, int firstDataRow)? FindFuelVehicleBlock(ExcelWorksheet ws, string vehicleSheetName)
        {
            if (ws.Dimension == null) return null;

            for (int row = 1; row <= Math.Min(10, ws.Dimension.End.Row); row++)
            {
                for (int col = 1; col <= ws.Dimension.End.Column; col++)
                {
                    var text = ws.Cells[row, col].Value?.ToString();
                    if (string.IsNullOrWhiteSpace(text)) continue;

                    // Excel側の見出し（例:"寝台車 29"）がDB側の車両シート名の末尾または一部と一致するか
                    if (!vehicleSheetName.EndsWith(text) && !vehicleSheetName.Contains(text)) continue;

                    // 見出しの下、数行以内で「日」ヘッダーの列を探す
                    for (int r2 = row + 1; r2 <= Math.Min(row + 4, ws.Dimension.End.Row); r2++)
                    {
                        for (int c2 = col; c2 <= Math.Min(col + 4, ws.Dimension.End.Column); c2++)
                        {
                            if (ws.Cells[r2, c2].Value?.ToString() == "日")
                                return (c2, c2 + 1, c2 + 2, r2 + 1);
                        }
                    }
                }
            }
            return null;
        }

        private void ProcessEastSheet(ExcelPackage wbInput, ExcelPackage wbShukei, string sheetName, ColumnMapping columnMap)
        {
            // [廃車済み車両対応] 該当シートが集計ファイルに無ければ自動生成してから書き込む
            var wsShukei = EnsureShukeiSheet(wbShukei, sheetName);
            if (wsShukei == null) return;
            var wsIn = wbInput.Workbook.Worksheets[sheetName];
            var shukeiMap = columnMap.ShukeiSheet;
            wsShukei.Cells[shukeiMap.Days].Value = wsIn.Cells[shukeiMap.Days].Value;
            wsShukei.Cells[shukeiMap.Hanso].Value = wsIn.Cells[shukeiMap.Hanso].Value;
            wsShukei.Cells[shukeiMap.YuryoKm].Value = wsIn.Cells[shukeiMap.YuryoKm].Value;
            wsShukei.Cells[shukeiMap.MuryoKm].Value = wsIn.Cells[shukeiMap.MuryoKm].Value;
            wsShukei.Cells[shukeiMap.Total].Value = wsIn.Cells[shukeiMap.Total].Value;
            Logger.Info($"[{sheetName}] の値を転記しました。");
        }

        private int FindTotalRow(ExcelWorksheet ws)
        {
            if (ws?.Dimension == null) return -1;
            for (int row = ws.Dimension.End.Row; row >= 3; row--) { if (ws.Cells[row, 1].Value?.ToString()?.Contains("合計") == true) return row; }
            return -1;
        }

        private int GetInt(object val) => val == null ? 0 : (int)Convert.ToDouble(val);
        private double GetDouble(object val) => val == null ? 0.0 : Convert.ToDouble(val);
    }
}