using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using HansoInputTool.Models;
using NLog;
using OfficeOpenXml;

namespace HansoInputTool.Services
{
    public class TransferProgressReport
    {
        public int Current { get; set; }
        public int Total { get; set; }
        public string Message { get; set; }
    }

    public partial class TransferService
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// [廃車済み車両対応] 転記中にEnsureShukeiSheetで自動生成された（＝現在のTemplate.xlsxには
        /// 存在しなかった）車両シート名の一覧。転記完了後、呼び出し側（MainViewModel）がこれを見て
        /// Input.xlsx側の車両設定からも削除するかどうかの判断に使う。
        /// </summary>
        public List<string> AutoGeneratedVehicleSheets { get; } = new List<string>();

        public async Task ExecuteAsync(
            string workInputFile,
            string bundledTemplateFile,
            string outputDir,
            int period,
            int month,
            int rNum,
            List<string> allSheetNames,
            Dictionary<string, RateInfo> rates,
            ColumnMapping columnMap,
            IProgress<TransferProgressReport> progress,
            FlagDefinitionService flagService = null,
            DatabaseService dbService = null,
            string eraName = "R",
            VehicleSettingsService vehicleSettingsService = null)
        {
            await Task.Run(() =>
            {
                string folderName = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報";
                string finalOutputDir = Path.Combine(outputDir, folderName);
                Directory.CreateDirectory(finalOutputDir);

                string geppoFilename = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報.xlsx";
                string geppoFilepath = Path.Combine(finalOutputDir, geppoFilename);
                File.Copy(workInputFile, geppoFilepath, true);
                Logger.Info($"実績月報ファイルをコピーしました: {geppoFilepath}");

                string shukeiFilename = $"{period}期 {month}月 {eraName}{rNum} アルス搬送・霊柩車　実績月報集計.xlsx";
                string shukeiFilepath = Path.Combine(finalOutputDir, shukeiFilename);
                File.Copy(bundledTemplateFile, shukeiFilepath, true);
                Logger.Info($"集計ファイルをコピーしました: {shukeiFilepath}");

                using var wbInput = new ExcelPackage(new FileInfo(workInputFile));
                using var wbGeppo = new ExcelPackage(new FileInfo(geppoFilepath));
                using var wbShukei = new ExcelPackage(new FileInfo(shukeiFilepath));

                // [出力側の不要シート削除] Template1/Template2はInput.xlsx側で車両シート追加時に
                // 使うひな形シートであり、配布用の実績月報には不要。Input.xlsx自体は一切変更せず、
                // 実績月報の出力ファイル（wbGeppo）側からのみ削除する。給油管理表は実際に給油記録が
                // 書き込まれるため、ここでは削除しない。
                foreach (var templateWs in wbGeppo.Workbook.Worksheets
                             .Where(ws => ExcelHandler.IsTemplateSheet(ws.Name))
                             .ToList())
                {
                    wbGeppo.Workbook.Worksheets.Delete(templateWs);
                    Logger.Info($"実績月報ファイル: ひな形シートを削除しました -> {templateWs.Name}");
                }

                // [給油管理表消失バグ対策] 「登録」シートに加えて、給油管理表・Template1/Template2
                // （ひな形）・月間集計も転記処理（車両シートとしての集計・自動生成判定）の対象から
                // 明示的に除外する。従来はキーワード不一致により結果的にスキップされる想定だったが、
                // 判定ロジックの意図しない変更に備え、ここでも明示的に除外しておく。
                var sheetsToProcess = allSheetNames?
                    .Where(s => !s.Contains("登録") && !ExcelHandler.IsProtectedSheet(s))
                    .ToList() ?? new List<string>();
                int totalSheets = sheetsToProcess.Count;
                int processedCount = 0;

                progress.Report(new TransferProgressReport { Current = 0, Total = totalSheets, Message = $"転記処理を開始します（対象: {totalSheets}シート）" });
                Logger.Info($"転記処理を開始: {totalSheets}シート");

                foreach (var sheetName in sheetsToProcess)
                {
                    progress.Report(new TransferProgressReport { Current = processedCount, Total = totalSheets, Message = $"[{processedCount + 1}/{totalSheets}] {sheetName} を処理中..." });

                    if (IsNormalSheet(sheetName))
                    {
                        ProcessNormalSheet(wbInput, wbGeppo, wbShukei, sheetName, rates, columnMap, flagService, dbService, vehicleSettingsService);
                    }
                    else if (IsEastSheet(sheetName))
                    {
                        ProcessEastSheet(wbInput, wbShukei, sheetName, columnMap);
                    }
                    else
                    {
                        Logger.Warn($"[{sheetName}] はどのシート種別にも該当しないためスキップしました。");
                    }

                    processedCount++;
                    Logger.Info($"[{sheetName}] 完了 ({processedCount}/{totalSheets})");
                }

                progress.Report(new TransferProgressReport { Current = processedCount, Total = totalSheets, Message = $"全{totalSheets}シートの転記が完了しました。保存中..." });

                // 全ての車両シート（寝台車・霊柩車・CH系）に対して
                // A1={eraName}{rNum}、B1=月 を書き込む（C1=期はファイル名に使用するのみ・セルへの記入は不要）
                foreach (var sheetWs in wbShukei.Workbook.Worksheets)
                {
                    string sn = sheetWs.Name;
                    if (IsNormalSheet(sn) || IsEastSheet(sn))
                    {
                        sheetWs.Cells["A1"].Value = $"{eraName}{rNum}";
                        sheetWs.Cells["B1"].Value = month;
                        Logger.Info($"集計ファイル [{sn}] に A1={eraName}{rNum}, B1={month} を書き込みました。");
                    }
                }
                foreach (var sheetWs in wbGeppo.Workbook.Worksheets)
                {
                    string sn = sheetWs.Name;
                    if (IsNormalSheet(sn) || IsEastSheet(sn))
                    {
                        sheetWs.Cells["A1"].Value = $"{eraName}{rNum}";
                        sheetWs.Cells["B1"].Value = month;
                        Logger.Info($"月報ファイル [{sn}] に A1={eraName}{rNum}, B1={month} を書き込みました。");
                    }
                }

                // [給油機能] DB使用時は給油記録を実績月報（wbGeppo）の給油管理表シートへ書き込む
                if (dbService != null)
                {
                    WriteFuelSheet(wbGeppo, dbService.GetAllFuelRecordsForCurrentSession());
                }

                // [並び替え対応] 自動生成された廃車済み車両シート等も含めて、
                // ①CH富士吉田→②CH大月→③CH東富士→④東日本セレモニーの順に並べ替える
                ReorderShukeiSheets(wbShukei);

                // [月間集計対応] 集計ファイルの「月間集計」シートは今まで自動更新されておらず、
                // 車両の追加・削除・廃車が反映されていなかったため、転記の都度、現在の車両構成で再作成する。
                UpdateShukeiMonthlySummary(wbInput, wbShukei, flagService, dbService);

                wbShukei.Save();
                wbGeppo.Save();

                // [No.6修正] TransferService内でのDBクリアを削除。
                // DBクリアは呼び出し元(MainViewModel.Transfer.cs)の転記完了後処理で一元管理する。
            });
        }

        // ===== シート種別の一元判定ヘルパー =====
        private static readonly string[] NormalSheetKeywords = { "寝台車", "霊柩車", "CH富士吉田", "CH大月", "CH東富士" };
        private static readonly string[] EastSheetKeywords  = { "東日本セレモニー", "東日本" };

        // シート順序：①CH富士吉田 → ②CH大月 → ③CH東富士 → ④東日本セレモニー
        private static readonly string[] BranchOrder = { "CH富士吉田", "CH大月", "CH東富士", "東日本セレモニー" };


        // ===== シート種別の一元判定ヘルパー（続き） =====
        private static bool IsNormalSheet(string sheetName) =>
            NormalSheetKeywords.Any(kw => sheetName.Contains(kw));

        private static bool IsEastSheet(string sheetName) =>
            EastSheetKeywords.Any(kw => sheetName.Contains(kw));
        // ==========================================

        // ===== 実績月報シート内の合計行を検索するヘルパー =====
        private int FindTotalRow(ExcelWorksheet ws)
        {
            if (ws?.Dimension == null) return -1;
            for (int row = ws.Dimension.End.Row; row >= 3; row--) { if (ws.Cells[row, 1].Value?.ToString()?.Contains("合計") == true) return row; }
            return -1;
        }
    }
}
